# =============================================================================
# word_database.py — The heart of the game
# Contains 100+ words per difficulty level, each with three levels of hints.
# =============================================================================

EASY_WORDS = [
    {"word": "computer", "meaning": "An electronic device for processing data.",
     "indirect_meaning": "A machine used for digital tasks.", "very_indirect_meaning": "An invention central to the information age."},
    {"word": "apple", "meaning": "A round fruit that grows on trees, often red or green.",
     "indirect_meaning": "A popular fruit associated with health.", "very_indirect_meaning": "It famously fell near a famous physicist."},
    {"word": "bread", "meaning": "A food made from baked dough, usually containing flour and water.",
     "indirect_meaning": "A staple food found on most breakfast tables.", "very_indirect_meaning": "Civilizations have made this since ancient times."},
    {"word": "chair", "meaning": "A piece of furniture designed for one person to sit on.",
     "indirect_meaning": "Something you find at a desk or dining table.", "very_indirect_meaning": "Four legs, a back, and a purpose."},
    {"word": "river", "meaning": "A large natural stream of water flowing towards an ocean or lake.",
     "indirect_meaning": "It carves landscapes over thousands of years.", "very_indirect_meaning": "Ancient civilizations thrived along its banks."},
    {"word": "cloud", "meaning": "A visible mass of water droplets floating in the sky.",
     "indirect_meaning": "It brings rain and shade on sunny days.", "very_indirect_meaning": "White or grey, it drifts above us all."},
    {"word": "music", "meaning": "Sounds arranged to create melody and rhythm for listening.",
     "indirect_meaning": "It influences mood and is enjoyed worldwide.", "very_indirect_meaning": "A universal language without words."},
    {"word": "plant", "meaning": "A living organism that grows in soil and makes its own food.",
     "indirect_meaning": "It takes in sunlight and releases oxygen.", "very_indirect_meaning": "The foundation of nearly every food chain."},
    {"word": "stone", "meaning": "A hard solid piece of rock or mineral matter.",
     "indirect_meaning": "Humans used it as a tool for millions of years.", "very_indirect_meaning": "The oldest building material known to man."},
    {"word": "ocean", "meaning": "A vast body of salt water that covers most of the Earth.",
     "indirect_meaning": "It regulates climate and holds most of Earth's water.", "very_indirect_meaning": "Deeper than mountains are tall, and older than memory."},
    {"word": "tiger", "meaning": "A large wild cat with orange fur and black stripes.",
     "indirect_meaning": "Asia's most powerful big cat predator.", "very_indirect_meaning": "Symbol of strength across many Asian cultures."},
    {"word": "window", "meaning": "A glass panel in a wall that allows light and air to pass through.",
     "indirect_meaning": "It gives you a view of the outside world.", "very_indirect_meaning": "Where light enters and the world is framed."},
    {"word": "butter", "meaning": "A soft yellow food made from churned cream, used for spreading.",
     "indirect_meaning": "A dairy product that melts on warm bread.", "very_indirect_meaning": "Farmers made it by agitating fresh cream."},
    {"word": "candle", "meaning": "A stick of wax with a wick that burns to give light.",
     "indirect_meaning": "Used for light before electricity was invented.", "very_indirect_meaning": "It melts slowly, giving warmth and glow."},
    {"word": "garden", "meaning": "A piece of land where flowers, vegetables, or plants are grown.",
     "indirect_meaning": "A place where people grow food or enjoy nature.", "very_indirect_meaning": "The ancient kings kept grand ones as symbols of power."},
    {"word": "mirror", "meaning": "A smooth surface that reflects images clearly.",
     "indirect_meaning": "It shows you exactly what you look like.", "very_indirect_meaning": "Made of glass and silver, it captures the truth."},
    {"word": "pocket", "meaning": "A small bag sewn into clothing to hold small items.",
     "indirect_meaning": "Where you store your keys or phone.", "very_indirect_meaning": "A simple invention that changed fashion forever."},
    {"word": "pencil", "meaning": "A thin writing instrument filled with graphite.",
     "indirect_meaning": "It writes and can be erased easily.", "very_indirect_meaning": "Invented when graphite was discovered in England."},
    {"word": "bottle", "meaning": "A container with a narrow neck used to hold liquids.",
     "indirect_meaning": "It holds your water or juice on the go.", "very_indirect_meaning": "Glass or plastic, it carries what you drink."},
    {"word": "bridge", "meaning": "A structure built over a gap or river to allow crossing.",
     "indirect_meaning": "Engineers build it to connect two sides.", "very_indirect_meaning": "Without it, rivers would divide cities."},
    {"word": "forest", "meaning": "A large area covered with trees and undergrowth.",
     "indirect_meaning": "A dense area of trees that is home to wildlife.", "very_indirect_meaning": "Lungs of the planet, full of ancient life."},
    {"word": "castle", "meaning": "A large medieval stone building with towers and walls.",
     "indirect_meaning": "Kings and queens lived in these for protection.", "very_indirect_meaning": "Built to withstand sieges in the middle ages."},
    {"word": "flower", "meaning": "The colorful part of a plant that blooms and often smells sweet.",
     "indirect_meaning": "Bees love visiting it to collect pollen.", "very_indirect_meaning": "Nature's most beautiful advertisement."},
    {"word": "hammer", "meaning": "A hand tool with a heavy head used for driving nails into surfaces.",
     "indirect_meaning": "A carpenter's most basic tool.", "very_indirect_meaning": "Thor's weapon was named after it."},
    {"word": "island", "meaning": "A piece of land surrounded by water on all sides.",
     "indirect_meaning": "A landmass completely encircled by sea.", "very_indirect_meaning": "Isolated, yet sometimes home to unique civilizations."},
    {"word": "jacket", "meaning": "A short coat worn to keep warm or for style.",
     "indirect_meaning": "You wear it over your shirt in cool weather.", "very_indirect_meaning": "It keeps your core warm while staying fashionable."},
    {"word": "kettle", "meaning": "A metal pot used for boiling water, usually with a handle and spout.",
     "indirect_meaning": "Used daily to make hot beverages.", "very_indirect_meaning": "The whistling kind announced teatime for generations."},
    {"word": "ladder", "meaning": "A structure with rungs used for climbing up or down.",
     "indirect_meaning": "Painters and firefighters use it often.", "very_indirect_meaning": "Two rails and many steps reaching for the sky."},
    {"word": "marble", "meaning": "A small glass ball used as a toy, or a type of hard decorative stone.",
     "indirect_meaning": "Children used to play games with tiny glass ones.", "very_indirect_meaning": "Sculptors carved masterpieces from the stone version."},
    {"word": "napkin", "meaning": "A piece of cloth or paper used to wipe hands and mouth while eating.",
     "indirect_meaning": "Found folded beside your plate at restaurants.", "very_indirect_meaning": "Table manners depend heavily on this little square."},
    {"word": "orange", "meaning": "A round citrus fruit with a tough orange-colored skin.",
     "indirect_meaning": "A juicy fruit rich in Vitamin C.", "very_indirect_meaning": "Named after its color, or is the color named after it?"},
    {"word": "pillow", "meaning": "A soft cushion used to rest your head while sleeping.",
     "indirect_meaning": "It makes sleeping comfortable at night.", "very_indirect_meaning": "Stuffed with feathers or foam for comfort."},
    {"word": "rabbit", "meaning": "A small furry mammal with long ears and a short tail.",
     "indirect_meaning": "This small fluffy animal hops and loves carrots.", "very_indirect_meaning": "Magicians pull it from hats; it reproduces very rapidly."},
    {"word": "rocket", "meaning": "A vehicle or missile powered by engine thrust.",
     "indirect_meaning": "It carries humans or satellites into space.", "very_indirect_meaning": "The result of decades of scientific ambition."},
    {"word": "spider", "meaning": "An eight-legged creature that spins webs to catch insects.",
     "indirect_meaning": "It builds traps made of silk to catch prey.", "very_indirect_meaning": "Some fear it; scientists study its silk."},
    {"word": "summer", "meaning": "The warmest season of the year, between spring and autumn.",
     "indirect_meaning": "Schools are often closed during this season.", "very_indirect_meaning": "Solstice marks its peak, beaches fill with life."},
    {"word": "tongue", "meaning": "The muscular organ in the mouth used for tasting and speaking.",
     "indirect_meaning": "It helps you taste food and form words.", "very_indirect_meaning": "Without it, language and flavor would be impossible."},
    {"word": "turtle", "meaning": "A reptile with a hard shell that protects its soft body.",
     "indirect_meaning": "This slow-moving creature lives to be very old.", "very_indirect_meaning": "Ancient mariners used them for navigation landmarks."},
    {"word": "violin", "meaning": "A four-stringed musical instrument played with a bow.",
     "indirect_meaning": "A classical instrument with a rich, resonant sound.", "very_indirect_meaning": "Mozart and Paganini made it sing."},
    {"word": "winter", "meaning": "The coldest season of the year, often bringing snow and frost.",
     "indirect_meaning": "Temperatures drop and people bundle up in this season.", "very_indirect_meaning": "The solstice brings its longest night."},
    {"word": "zipper", "meaning": "A fastening device with interlocking teeth used on clothing.",
     "indirect_meaning": "It opens and closes jackets and bags smoothly.", "very_indirect_meaning": "Invented in the 1890s and forever changed fashion."},
    {"word": "anchor", "meaning": "A heavy object dropped to the seabed to hold a ship in place.",
     "indirect_meaning": "Sailors use it to stop a boat from drifting.", "very_indirect_meaning": "Symbol of stability and hope in maritime culture."},
    {"word": "blanket", "meaning": "A large piece of thick cloth used to keep warm while sleeping.",
     "indirect_meaning": "You wrap it around yourself on cold nights.", "very_indirect_meaning": "Comfort personified in woven form."},
    {"word": "camera", "meaning": "A device used to capture photographs or record video.",
     "indirect_meaning": "You use it to take pictures of memories.", "very_indirect_meaning": "Invented in the 1800s, it froze time forever."},
    {"word": "desert", "meaning": "A very dry, sandy landscape with little rainfall and few plants.",
     "indirect_meaning": "A barren landscape where little water exists.", "very_indirect_meaning": "Civilizations have always feared and crossed it."},
    {"word": "engine", "meaning": "A machine that converts energy into mechanical motion.",
     "indirect_meaning": "It powers cars, trains, and ships.", "very_indirect_meaning": "The industrial revolution turned on this invention."},
    {"word": "finger", "meaning": "One of the five digits on a human hand.",
     "indirect_meaning": "You use these to type, point, and grip things.", "very_indirect_meaning": "Each carries a unique print, unlike any other."},
    {"word": "gloves", "meaning": "Coverings worn on the hands to protect them from cold or dirt.",
     "indirect_meaning": "Worn by surgeons, cooks, and boxers alike.", "very_indirect_meaning": "A symbol of elegance in Victorian society."},
    {"word": "helmet", "meaning": "A hard hat worn to protect the head from injury.",
     "indirect_meaning": "Cyclists, soldiers, and motorcyclists wear these.", "very_indirect_meaning": "Warriors have worn head protection since antiquity."},
    {"word": "insect", "meaning": "A small creature with six legs and usually one or two pairs of wings.",
     "indirect_meaning": "Bees, ants, and butterflies belong to this group.", "very_indirect_meaning": "The most numerous and diverse animals on Earth."},
    {"word": "jungle", "meaning": "A dense tropical forest with a lot of vegetation and wildlife.",
     "indirect_meaning": "A thick, hot forest full of exotic animals.", "very_indirect_meaning": "Where ancient civilizations hid, and wildlife thrives."},
    {"word": "knife", "meaning": "A sharp tool with a blade used for cutting food or other materials.",
     "indirect_meaning": "Found in every kitchen for food preparation.", "very_indirect_meaning": "One of humanity's oldest and most essential tools."},
    {"word": "lemon", "meaning": "A sour yellow citrus fruit used in cooking and drinks.",
     "indirect_meaning": "Its juice adds sourness to food and beverages.", "very_indirect_meaning": "Sailors used it to prevent a deadly vitamin deficiency."},
    {"word": "medal", "meaning": "A metal disc awarded for achievement in a competition or event.",
     "indirect_meaning": "Athletes receive these for winning at competitions.", "very_indirect_meaning": "Gold, silver, or bronze — each tells a story of effort."},
    {"word": "nurse", "meaning": "A trained healthcare professional who cares for patients.",
     "indirect_meaning": "They assist doctors and provide medical care.", "very_indirect_meaning": "Florence Nightingale transformed this noble profession."},
    {"word": "olive", "meaning": "A small oval fruit, usually green or black, used in cooking.",
     "indirect_meaning": "Its oil is central to Mediterranean cuisine.", "very_indirect_meaning": "Pressed into oil, it fueled ancient lamps and kitchens."},
    {"word": "paint", "meaning": "A colored liquid applied to surfaces to add color or protection.",
     "indirect_meaning": "Artists use it to create pictures on canvas.", "very_indirect_meaning": "Cave dwellers were the first to use it."},
    {"word": "queen", "meaning": "A female ruler of a kingdom or the wife of a king.",
     "indirect_meaning": "She wears a crown and rules a country.", "very_indirect_meaning": "The most powerful piece on a chessboard."},
    {"word": "radio", "meaning": "A device that receives and broadcasts sound through electromagnetic waves.",
     "indirect_meaning": "It plays music and broadcasts news without the internet.", "very_indirect_meaning": "Marconi's invention connected the world wirelessly."},
    {"word": "shirt", "meaning": "A garment worn on the upper body, typically with buttons.",
     "indirect_meaning": "One of the most common pieces of clothing worn daily.", "very_indirect_meaning": "A basic wardrobe staple across all cultures."},
    {"word": "train", "meaning": "A vehicle that runs on rails and carries passengers or goods.",
     "indirect_meaning": "It travels on tracks between cities and towns.", "very_indirect_meaning": "The industrial revolution rode on its back."},
    {"word": "umbrella", "meaning": "A device held over the head to protect from rain or sun.",
     "indirect_meaning": "You carry it on a rainy day to stay dry.", "very_indirect_meaning": "A British icon of politeness and rain preparedness."},
    {"word": "valley", "meaning": "A low area of land between hills or mountains.",
     "indirect_meaning": "Rivers often flow through this type of terrain.", "very_indirect_meaning": "Where ancient settlements gathered for water."},
    {"word": "wagon", "meaning": "A four-wheeled vehicle pulled by horses or pushed by hand.",
     "indirect_meaning": "It was used before automobiles to carry goods.", "very_indirect_meaning": "Pioneers traveled west in these covered vehicles."},
    {"word": "yeast", "meaning": "A microorganism used to make bread rise and ferment beverages.",
     "indirect_meaning": "Bakers use it to make dough puff up.", "very_indirect_meaning": "Without it, bread would be flat and beer non-existent."},
    {"word": "zebra", "meaning": "An African animal that looks like a horse with black and white stripes.",
     "indirect_meaning": "An African animal famous for its distinctive pattern.", "very_indirect_meaning": "No two share the same pattern, like fingerprints."},
    {"word": "alarm", "meaning": "A device that makes a loud sound to wake you up or warn of danger.",
     "indirect_meaning": "It wakes you up in the morning.", "very_indirect_meaning": "Cities have sirens; you have this on your bedside."},
    {"word": "basin", "meaning": "A wide, open container used for washing or holding water.",
     "indirect_meaning": "You might wash your hands in it.", "very_indirect_meaning": "Also used to describe a low-lying geographic area."},
    {"word": "coral", "meaning": "A marine invertebrate that forms colorful reefs underwater.",
     "indirect_meaning": "Found in warm seas, it forms colorful underwater structures.", "very_indirect_meaning": "Called the rainforests of the sea."},
    {"word": "dairy", "meaning": "Products made from milk, such as cheese, butter, or yogurt.",
     "indirect_meaning": "Milk-based products like cheese and yogurt.", "very_indirect_meaning": "A whole industry built on the cow."},
    {"word": "eagle", "meaning": "A large bird of prey with a sharp beak and excellent eyesight.",
     "indirect_meaning": "A large bird known for its sharp vision and strength.", "very_indirect_meaning": "Symbol of freedom for many nations."},
    {"word": "fence", "meaning": "A barrier made of wood, metal, or wire used to enclose an area.",
     "indirect_meaning": "It marks the boundary of a property.", "very_indirect_meaning": "Good ones make good neighbors."},
    {"word": "globe", "meaning": "A spherical model of the Earth.",
     "indirect_meaning": "A round model of our planet used in classrooms.", "very_indirect_meaning": "It shows every country, ocean, and mountain range."},
    {"word": "honey", "meaning": "A sweet, sticky substance made by bees from flower nectar.",
     "indirect_meaning": "A natural sweetener produced by bees.", "very_indirect_meaning": "Archaeologists found 3000-year-old jars of it in Egypt."},
    {"word": "igloo", "meaning": "A dome-shaped shelter built from blocks of snow.",
     "indirect_meaning": "A snow house built by indigenous Arctic peoples.", "very_indirect_meaning": "Warm inside despite being made entirely of ice."},
    {"word": "jelly", "meaning": "A soft, clear food made from fruit juice and gelatin.",
     "indirect_meaning": "A wobbly, sweet spread often paired with peanut butter.", "very_indirect_meaning": "Its texture comes from proteins extracted from animal bones."},
    {"word": "koala", "meaning": "A small marsupial native to Australia that lives in eucalyptus trees.",
     "indirect_meaning": "An Australian animal that sleeps up to 22 hours a day.", "very_indirect_meaning": "It survives on leaves toxic to most other animals."},
    {"word": "laser", "meaning": "A device that emits a focused beam of light.",
     "indirect_meaning": "A device used in surgery, cutting, and scanning.", "very_indirect_meaning": "Coherent light harnessed by scientists in the 1960s."},
    {"word": "melon", "meaning": "A large, sweet fruit with a hard rind and juicy flesh.",
     "indirect_meaning": "A refreshing summer fruit with green or orange flesh.", "very_indirect_meaning": "Its water content is what makes summer bearable."},
    {"word": "nerve", "meaning": "A strand of tissue in the body that transmits signals.",
     "indirect_meaning": "It carries messages between the brain and body.", "very_indirect_meaning": "The wiring system of the human body."},
    {"word": "orbit", "meaning": "The curved path an object takes around a planet or star.",
     "indirect_meaning": "The path the Earth takes around the Sun.", "very_indirect_meaning": "Gravity bends the straight line into a circle."},
    {"word": "pearl", "meaning": "A hard, shiny ball formed inside an oyster, used in jewelry.",
     "indirect_meaning": "A precious gem formed inside a sea creature.", "very_indirect_meaning": "Irritation became beauty inside a shell."},
    {"word": "quilt", "meaning": "A thick blanket made by sewing together layers of fabric.",
     "indirect_meaning": "A patchwork blanket often made by hand.", "very_indirect_meaning": "American pioneers stitched them from old clothing."},
    {"word": "reindeer", "meaning": "A large deer from cold northern regions, associated with Christmas.",
     "indirect_meaning": "Santa's famous flying animals.", "very_indirect_meaning": "Indigenous northern peoples depend on them for survival."},
    {"word": "salmon", "meaning": "A large pink fish that swims upstream to spawn.",
     "indirect_meaning": "A popular pinkish fish known for swimming against the current.", "very_indirect_meaning": "It returns to its birthplace to give life before dying."},
    {"word": "thorn", "meaning": "A sharp pointed growth on a plant stem.",
     "indirect_meaning": "The sharp spike on a rose stem.", "very_indirect_meaning": "Nature's warning sign on its most beautiful plants."},
    {"word": "urban", "meaning": "Relating to or located in a city or town.",
     "indirect_meaning": "Describing something that belongs to city life.", "very_indirect_meaning": "The opposite of rural, where millions cluster."},
    {"word": "vapor", "meaning": "Water in the form of a gas, especially when visible as steam or mist.",
     "indirect_meaning": "The gas form of water rising from a hot surface.", "very_indirect_meaning": "The invisible state of water that forms clouds."},
    {"word": "wheat", "meaning": "A grain crop used to make flour for bread and pasta.",
     "indirect_meaning": "The grain from which flour and bread are made.", "very_indirect_meaning": "Agriculture was born when humans began to cultivate it."},
    {"word": "yacht", "meaning": "A large, luxurious boat used for racing or leisure sailing.",
     "indirect_meaning": "A fancy boat used by wealthy people for sailing.", "very_indirect_meaning": "The playground of billionaires on open water."},
    {"word": "actor", "meaning": "A person who performs in plays, films, or television.",
     "indirect_meaning": "Someone who plays a character in a movie or show.", "very_indirect_meaning": "Their craft involves living another person's life."},
    {"word": "badge", "meaning": "A small piece of metal or cloth used to identify someone.",
     "indirect_meaning": "Police officers and security guards wear these.", "very_indirect_meaning": "A symbol of authority or achievement pinned to a chest."},
    {"word": "chalk", "meaning": "A soft white or colored stick used for writing on blackboards.",
     "indirect_meaning": "Teachers use it to write on blackboards.", "very_indirect_meaning": "Made from ancient sea creature shells compressed over millennia."},
    {"word": "diary", "meaning": "A personal book where someone writes their daily thoughts and events.",
     "indirect_meaning": "A private journal where you record daily experiences.", "very_indirect_meaning": "Anne Frank's hid truths the world needed to hear."},
    {"word": "elbow", "meaning": "The joint in the middle of the arm that allows it to bend.",
     "indirect_meaning": "The bony joint that connects your upper and lower arm.", "very_indirect_meaning": "You lean on tables with it; plumbers call corners by its name."},
    {"word": "fence", "meaning": "A structure made of posts and wire or wood used as a boundary.",
     "indirect_meaning": "A barrier that marks the edge of a property.", "very_indirect_meaning": "Neighbors argue about who should build and maintain it."},
    {"word": "grain", "meaning": "A small, hard seed from a cereal plant like wheat or rice.",
     "indirect_meaning": "The small seed from which bread and rice are made.", "very_indirect_meaning": "Entire empires were built on controlling this."},
    {"word": "hinge", "meaning": "A jointed device that allows a door or lid to swing open.",
     "indirect_meaning": "What allows a door to open and close smoothly.", "very_indirect_meaning": "A small piece of metal on which everything pivots."},
    {"word": "ivory", "meaning": "A hard white material made from the tusks of elephants.",
     "indirect_meaning": "A valuable white material from elephant tusks.", "very_indirect_meaning": "Its trade drove elephants toward extinction."},
]

MEDIUM_WORDS = [
    {"word": "algorithm", "meaning": "A step-by-step procedure for solving a problem.",
     "indirect_meaning": "The logic behind how computers solve tasks.", "very_indirect_meaning": "Every Google search runs on one you'll never see."},
    {"word": "ambiguous", "meaning": "Open to more than one interpretation; unclear.",
     "indirect_meaning": "When a statement can be understood in multiple ways.", "very_indirect_meaning": "Great literature thrives in its shadow."},
    {"word": "telescope", "meaning": "An instrument used to observe distant objects, especially stars.",
     "indirect_meaning": "Scientists use it to study the night sky.", "very_indirect_meaning": "Galileo's version changed humanity's place in the universe."},
    {"word": "hibernate", "meaning": "To spend the winter in a dormant or sleep-like state.",
     "indirect_meaning": "What bears do during cold months.", "very_indirect_meaning": "A biological trick to survive when food is scarce."},
    {"word": "symphony", "meaning": "A long musical composition for a full orchestra.",
     "indirect_meaning": "A large-scale musical work performed by orchestras.", "very_indirect_meaning": "Beethoven wrote nine, the last while deaf."},
    {"word": "democracy", "meaning": "A system of government where citizens vote to elect leaders.",
     "indirect_meaning": "A form of government where people choose their leaders.", "very_indirect_meaning": "Ancient Athens invented it; the world still debates it."},
    {"word": "bacteria", "meaning": "Microscopic single-celled organisms found everywhere.",
     "indirect_meaning": "Tiny organisms invisible to the eye that can cause or prevent disease.", "very_indirect_meaning": "They predate all life on Earth and outnumber us a trillion to one."},
    {"word": "geography", "meaning": "The study of Earth's physical features and human populations.",
     "indirect_meaning": "A school subject that covers maps, climates, and countries.", "very_indirect_meaning": "It shaped every civilization that ever existed."},
    {"word": "philosophy", "meaning": "The study of knowledge, reality, and the nature of existence.",
     "indirect_meaning": "A field of study asking the deepest questions about life.", "very_indirect_meaning": "Socrates died rather than abandon his pursuit of it."},
    {"word": "satellite", "meaning": "An object that orbits a planet, either natural or man-made.",
     "indirect_meaning": "A device launched into space to relay signals or gather data.", "very_indirect_meaning": "Every GPS signal you use travels through one."},
    {"word": "evolution", "meaning": "The process by which species change over time through natural selection.",
     "indirect_meaning": "The gradual change in species through generations.", "very_indirect_meaning": "Darwin observed it on isolated islands."},
    {"word": "nutrition", "meaning": "The process of providing or obtaining food for health.",
     "indirect_meaning": "The science of how food affects the human body.", "very_indirect_meaning": "Vitamins, proteins, fats — the body's fuel system."},
    {"word": "ambition", "meaning": "A strong desire to achieve something great.",
     "indirect_meaning": "The driving force behind great achievements.", "very_indirect_meaning": "Shakespeare called it the soldier's virtue."},
    {"word": "blueprint", "meaning": "A detailed plan or technical drawing for a structure.",
     "indirect_meaning": "An architect's detailed plan for a building.", "very_indirect_meaning": "Before anything is built, this is drawn."},
    {"word": "chemical", "meaning": "A substance with a specific molecular composition, often used in science or industry.",
     "indirect_meaning": "A substance studied in labs that can be useful or harmful.", "very_indirect_meaning": "Mendeleev organized all of them in a single table."},
    {"word": "diplomat", "meaning": "An official who represents a country in foreign affairs.",
     "indirect_meaning": "A person who negotiates between governments.", "very_indirect_meaning": "They avoid wars with words and handshakes."},
    {"word": "equation", "meaning": "A mathematical statement showing two expressions are equal.",
     "indirect_meaning": "A mathematical sentence with an equal sign.", "very_indirect_meaning": "Einstein's most famous one changed physics forever."},
    {"word": "financial", "meaning": "Relating to money, banking, and economic matters.",
     "indirect_meaning": "Describing anything related to money or banking.", "very_indirect_meaning": "Wall Street speaks in this language fluently."},
    {"word": "glacier", "meaning": "A large, slow-moving river of ice formed from compacted snow.",
     "indirect_meaning": "A massive body of ice that moves slowly over land.", "very_indirect_meaning": "They carved valleys and lakes over thousands of years."},
    {"word": "heritage", "meaning": "Traditions and values passed down from previous generations.",
     "indirect_meaning": "The cultural history and traditions of a people.", "very_indirect_meaning": "What a civilization leaves to its descendants."},
    {"word": "invasion", "meaning": "An armed attack on a country by another country's forces.",
     "indirect_meaning": "When one country's military enters another by force.", "very_indirect_meaning": "D-Day was history's most famous one."},
    {"word": "jealousy", "meaning": "The feeling of resentment toward someone for what they have.",
     "indirect_meaning": "The emotion of wanting what someone else has.", "very_indirect_meaning": "Shakespeare called it the green-eyed monster."},
    {"word": "knowledge", "meaning": "Facts, information, and skills acquired through learning.",
     "indirect_meaning": "Everything learned through education and experience.", "very_indirect_meaning": "Bacon said it was power; libraries hold it."},
    {"word": "labyrinth", "meaning": "A complicated network of paths from which it is difficult to escape.",
     "indirect_meaning": "A complex maze with many confusing paths.", "very_indirect_meaning": "The Minotaur lived in the most famous one."},
    {"word": "magnitude", "meaning": "The great size or extent of something; importance or scale.",
     "indirect_meaning": "The scale or size of something significant.", "very_indirect_meaning": "Earthquake strength is measured on its scale."},
    {"word": "navigator", "meaning": "A person who plans and directs the course of a ship or aircraft.",
     "indirect_meaning": "Someone who guides a vessel or vehicle along a route.", "very_indirect_meaning": "Before GPS, they used stars to cross oceans."},
    {"word": "obsession", "meaning": "An unhealthy fixation on something or someone.",
     "indirect_meaning": "When a thought or idea takes over your mind completely.", "very_indirect_meaning": "Artists, scientists, and villains share this trait."},
    {"word": "pandemic", "meaning": "A disease that spreads across multiple countries or continents.",
     "indirect_meaning": "A global outbreak of a contagious disease.", "very_indirect_meaning": "The Spanish flu and COVID-19 both earned this label."},
    {"word": "quantum", "meaning": "The smallest discrete unit of energy in quantum mechanics.",
     "indirect_meaning": "A concept in physics relating to the smallest particles.", "very_indirect_meaning": "At this scale, particles exist in multiple states at once."},
    {"word": "radiation", "meaning": "Energy emitted in the form of waves or particles.",
     "indirect_meaning": "Energy released by radioactive material or electromagnetic sources.", "very_indirect_meaning": "Marie Curie discovered it and died because of it."},
    {"word": "sculpture", "meaning": "A three-dimensional work of art made by carving, molding, or assembling material.",
     "indirect_meaning": "A three-dimensional artwork made by a sculptor.", "very_indirect_meaning": "Michelangelo said he just removed what was unnecessary."},
    {"word": "tradition", "meaning": "A custom or belief passed down through generations.",
     "indirect_meaning": "A practice that has been done the same way for a long time.", "very_indirect_meaning": "G.K. Chesterton called it democracy of the dead."},
    {"word": "universal", "meaning": "Relating to or done by all people or things in the world.",
     "indirect_meaning": "Something that applies to everyone everywhere.", "very_indirect_meaning": "Gravity and mathematics are considered this."},
    {"word": "volunteer", "meaning": "A person who offers to do work without being paid.",
     "indirect_meaning": "Someone who freely gives their time to help others.", "very_indirect_meaning": "They built some of history's greatest communities."},
    {"word": "wilderness", "meaning": "A wild, natural area untouched by humans.",
     "indirect_meaning": "Vast natural land without roads or buildings.", "very_indirect_meaning": "Thoreau went here to find what was essential."},
    {"word": "xylophone", "meaning": "A musical instrument played by striking wooden bars.",
     "indirect_meaning": "A percussion instrument with bars struck by mallets.", "very_indirect_meaning": "Its name is Greek for 'wooden sound.'"},
    {"word": "yesterday", "meaning": "The day immediately before today.",
     "indirect_meaning": "The day that has just passed before today.", "very_indirect_meaning": "Beatles wrote a song about it; regret lives in it."},
    {"word": "zoologist", "meaning": "A scientist who studies the behavior and biology of animals.",
     "indirect_meaning": "A scientist who studies and classifies animals.", "very_indirect_meaning": "Darwin was essentially one, though the title came later."},
    {"word": "atmosphere", "meaning": "The layers of gas surrounding a planet, especially Earth.",
     "indirect_meaning": "The air and gases that surround the Earth.", "very_indirect_meaning": "It shields us from cosmic radiation and keeps us breathing."},
    {"word": "biography", "meaning": "A written account of someone else's life.",
     "indirect_meaning": "A book that tells the true story of another person's life.", "very_indirect_meaning": "It immortalizes its subject in ink and memory."},
    {"word": "civilize", "meaning": "To bring a place or people to a stage of social development.",
     "indirect_meaning": "To develop culture, order, and social structure.", "very_indirect_meaning": "Empires believed it was their duty; historians disagree."},
    {"word": "dedicate", "meaning": "To commit fully to a task or person.",
     "indirect_meaning": "To devote time and effort to something important.", "very_indirect_meaning": "Every masterpiece required this from its creator."},
    {"word": "educate", "meaning": "To provide systematic instruction or training.",
     "indirect_meaning": "To teach and develop someone's knowledge or skills.", "very_indirect_meaning": "The most powerful weapon, according to Mandela."},
    {"word": "festival", "meaning": "A day or period of celebration, often with public activities.",
     "indirect_meaning": "A large public celebration with music, food, and events.", "very_indirect_meaning": "Cultures define themselves by what they celebrate."},
    {"word": "gravity", "meaning": "The force that attracts objects toward the center of the Earth.",
     "indirect_meaning": "The invisible force that keeps us on the ground.", "very_indirect_meaning": "Newton reportedly noticed it via a falling apple."},
    {"word": "humility", "meaning": "The quality of being modest and respectful.",
     "indirect_meaning": "The act of not thinking too highly of yourself.", "very_indirect_meaning": "The greatest leaders often possess it most."},
    {"word": "identity", "meaning": "The characteristics that define who someone or something is.",
     "indirect_meaning": "The unique set of traits that make you who you are.", "very_indirect_meaning": "Philosophers have debated its nature for millennia."},
    {"word": "judgment", "meaning": "The ability to make considered decisions or conclusions.",
     "indirect_meaning": "The act of forming an opinion based on evidence.", "very_indirect_meaning": "Courts exist because human reason needs structure."},
    {"word": "kinetic", "meaning": "Relating to the energy of motion.",
     "indirect_meaning": "Describing energy that comes from movement.", "very_indirect_meaning": "A rolling ball has this; a still one has potential."},
    {"word": "landmark", "meaning": "A prominent object or feature that marks a location.",
     "indirect_meaning": "A recognizable building or structure that defines a place.", "very_indirect_meaning": "Cities are remembered by their most famous ones."},
    {"word": "mechanic", "meaning": "A person who maintains and repairs machinery.",
     "indirect_meaning": "Someone who fixes engines and mechanical problems.", "very_indirect_meaning": "The Industrial Revolution created this profession."},
    {"word": "neurosis", "meaning": "A mental disorder causing anxiety and stress.",
     "indirect_meaning": "A mental condition involving persistent worry or fear.", "very_indirect_meaning": "Freud built a career studying its roots."},
    {"word": "outbreak", "meaning": "A sudden occurrence of something harmful, like a disease.",
     "indirect_meaning": "When a disease or event spreads rapidly and unexpectedly.", "very_indirect_meaning": "Epidemiologists race to stop it before it becomes a pandemic."},
    {"word": "portrait", "meaning": "A painting, drawing, or photograph of a person.",
     "indirect_meaning": "A visual representation of a specific person.", "very_indirect_meaning": "The Mona Lisa is history's most famous one."},
    {"word": "quarantine", "meaning": "Isolation imposed to prevent spread of disease.",
     "indirect_meaning": "Separation of a person to prevent spreading illness.", "very_indirect_meaning": "Ships were held offshore for 40 days; the word comes from that number."},
    {"word": "republic", "meaning": "A state governed by elected representatives and an elected president.",
     "indirect_meaning": "A government system with elected leaders, not a monarch.", "very_indirect_meaning": "Rome was one; America was modeled on that idea."},
    {"word": "spectrum", "meaning": "A range of values or characteristics arranged in order.",
     "indirect_meaning": "A range from one extreme to another, like colors in a rainbow.", "very_indirect_meaning": "Newton revealed it when he split light through a prism."},
    {"word": "tribunal", "meaning": "A court or committee appointed to judge a specific matter.",
     "indirect_meaning": "A special court set up to make official rulings.", "very_indirect_meaning": "Nuremberg's were among the most consequential in history."},
    {"word": "unanimous", "meaning": "Agreed upon by everyone without exception.",
     "indirect_meaning": "When every person in a group agrees on something.", "very_indirect_meaning": "Jury verdicts are most powerful in this form."},
    {"word": "vibration", "meaning": "A rapid oscillation or shaking back and forth.",
     "indirect_meaning": "The rapid back-and-forth movement that creates sound.", "very_indirect_meaning": "Sound is nothing more than this in the air."},
    {"word": "waterfall", "meaning": "A cascade of water falling from a height.",
     "indirect_meaning": "A natural feature where water falls from a cliff.", "very_indirect_meaning": "Niagara and Victoria made nations famous."},
    {"word": "xenophobia", "meaning": "Fear or hatred of strangers or foreigners.",
     "indirect_meaning": "Hostility or prejudice toward people from other countries.", "very_indirect_meaning": "Historically, empires often spread this fear."},
    {"word": "yearning", "meaning": "A deep longing or desire for something.",
     "indirect_meaning": "An intense feeling of wanting something deeply.", "very_indirect_meaning": "Poets have described it as an ache of the soul."},
    {"word": "zeppelin", "meaning": "A type of large, rigid airship.",
     "indirect_meaning": "A massive German airship used in early aviation.", "very_indirect_meaning": "The Hindenburg disaster ended its era dramatically."},
    {"word": "abundance", "meaning": "A very large quantity of something.",
     "indirect_meaning": "When something exists in very large amounts.", "very_indirect_meaning": "Agricultural revolution created it for the first time."},
    {"word": "boundary", "meaning": "A line that marks the limits of an area.",
     "indirect_meaning": "A line separating one area, country, or concept from another.", "very_indirect_meaning": "Empires rose and fell over where to draw it."},
    {"word": "catalyst", "meaning": "A substance that increases the rate of a chemical reaction.",
     "indirect_meaning": "Something that causes or speeds up change.", "very_indirect_meaning": "In chemistry and history, it sets things in motion."},
    {"word": "dilemma", "meaning": "A situation requiring a difficult choice between two options.",
     "indirect_meaning": "A situation where you must choose between two bad options.", "very_indirect_meaning": "Philosophers invented thought experiments around it."},
    {"word": "eloquent", "meaning": "Fluent or persuasive in speaking or writing.",
     "indirect_meaning": "Describing someone who speaks clearly and persuasively.", "very_indirect_meaning": "Lincoln and Churchill were legendary for it."},
    {"word": "folklore", "meaning": "Traditional stories, customs, and beliefs of a community.",
     "indirect_meaning": "Stories and legends passed down through generations.", "very_indirect_meaning": "It survived before writing by traveling mouth to ear."},
    {"word": "gradient", "meaning": "A gradual change in the value of a quantity.",
     "indirect_meaning": "A gradual slope or transition between two values.", "very_indirect_meaning": "In machine learning, it guides the algorithm toward truth."},
    {"word": "hallmark", "meaning": "A mark stamped on precious metals to indicate quality.",
     "indirect_meaning": "A distinctive feature that identifies quality or authenticity.", "very_indirect_meaning": "In medieval goldsmithing, it was a guarantee of purity."},
    {"word": "ideology", "meaning": "A system of ideas and ideals forming the basis of a political or economic theory.",
     "indirect_meaning": "A set of beliefs that guide political and social thinking.", "very_indirect_meaning": "Communism, capitalism, and fascism are all examples."},
    {"word": "judiciary", "meaning": "The branch of government responsible for the court system.",
     "indirect_meaning": "The branch of government that interprets and applies the law.", "very_indirect_meaning": "Montesquieu argued it must remain independent."},
    {"word": "kaleidoscope", "meaning": "A tube with mirrors that produces colorful, changing patterns.",
     "indirect_meaning": "A toy with mirrors that creates shifting colorful patterns.", "very_indirect_meaning": "A metaphor for chaotic beauty in constant change."},
    {"word": "laborious", "meaning": "Requiring considerable time and effort.",
     "indirect_meaning": "Describing a task that is long and very hard to do.", "very_indirect_meaning": "Building the pyramids was undeniably this."},
    {"word": "manifest", "meaning": "Clear and obvious; or to display a quality clearly.",
     "indirect_meaning": "Something that becomes visible or clearly apparent.", "very_indirect_meaning": "America's westward expansion was called its Destiny."},
    {"word": "narcissism", "meaning": "Excessive self-love or self-admiration.",
     "indirect_meaning": "An extreme focus on oneself and personal gain.", "very_indirect_meaning": "Named after a Greek boy who fell in love with his reflection."},
    {"word": "nostalgia", "meaning": "A sentimental longing for the past.",
     "indirect_meaning": "The feeling of fondly remembering the good old days.", "very_indirect_meaning": "Marketing experts have weaponized it for decades."},
    {"word": "ominous", "meaning": "Giving the impression that something bad is about to happen.",
     "indirect_meaning": "Something that feels like a bad sign or warning.", "very_indirect_meaning": "Dark clouds gathering are nature's version of it."},
    {"word": "paradigm", "meaning": "A typical example or model; a framework of thinking.",
     "indirect_meaning": "A standard model or framework for thinking about something.", "very_indirect_meaning": "Kuhn argued that science advances by shifting between them."},
    {"word": "quandary", "meaning": "A state of uncertainty or puzzlement.",
     "indirect_meaning": "When you are confused and unsure what to do next.", "very_indirect_meaning": "Hamlet lived in one for an entire play."},
    {"word": "resilience", "meaning": "The ability to recover quickly from difficulties.",
     "indirect_meaning": "The ability to bounce back after hardship.", "very_indirect_meaning": "Psychologists say it is the key to mental health."},
    {"word": "sovereign", "meaning": "A supreme ruler, especially a monarch.",
     "indirect_meaning": "A ruler with complete authority over a territory.", "very_indirect_meaning": "In democracies, 'the people' hold this power."},
    {"word": "tyranny", "meaning": "Cruel and oppressive rule by a leader.",
     "indirect_meaning": "When a ruler governs through fear and absolute power.", "very_indirect_meaning": "The American founders feared it above all else."},
    {"word": "utopian", "meaning": "Relating to an imagined perfect society.",
     "indirect_meaning": "Describing an idealistic, perfect world that may not be achievable.", "very_indirect_meaning": "Thomas More coined the word in 1516."},
    {"word": "vigilance", "meaning": "The action or state of keeping careful watch for danger.",
     "indirect_meaning": "Staying alert and watchful to avoid threats.", "very_indirect_meaning": "Security forces and parents share this quality."},
    {"word": "wanderlust", "meaning": "A strong desire to travel and explore the world.",
     "indirect_meaning": "A deep urge to explore new places and cultures.", "very_indirect_meaning": "A German word adopted by every traveler's heart."},
    {"word": "xenial", "meaning": "Friendly to strangers or foreigners; hospitable.",
     "indirect_meaning": "Being warm and welcoming to people you don't know.", "very_indirect_meaning": "Ancient Greeks made hospitality a sacred duty."},
    {"word": "zeal", "meaning": "Great energy or enthusiasm for a cause or goal.",
     "indirect_meaning": "Intense passion or dedication toward something.", "very_indirect_meaning": "Reformers and missionaries are known for having it."},
    {"word": "archive", "meaning": "A collection of historical documents and records.",
     "indirect_meaning": "A place where historical documents are stored and preserved.", "very_indirect_meaning": "Libraries and museums are the civilization's memory."},
    {"word": "benevolent", "meaning": "Well-meaning and kindly in disposition.",
     "indirect_meaning": "Describing someone who is kind and generous by nature.", "very_indirect_meaning": "The best rulers in history were remembered as this."},
    {"word": "chronicle", "meaning": "A factual written account of events in historical order.",
     "indirect_meaning": "A detailed record of events over a period of time.", "very_indirect_meaning": "Medieval monks wrote them by candlelight for centuries."},
    {"word": "dominion", "meaning": "Power or control over territory or people.",
     "indirect_meaning": "Control or authority over a large area or group.", "very_indirect_meaning": "Empires were defined by the extent of theirs."},
    {"word": "enigma", "meaning": "A person or thing that is mysterious and difficult to understand.",
     "indirect_meaning": "Something or someone that is deeply mysterious.", "very_indirect_meaning": "The Sphinx asked questions about one; WWII coded messages used its name."},
]

HARD_WORDS = [
    {"word": "ephemeral", "meaning": "Lasting for a very short time; transitory.",
     "indirect_meaning": "Something fleeting that disappears quickly.", "very_indirect_meaning": "Cherry blossoms are its living metaphor."},
    {"word": "perspicacious", "meaning": "Having a ready insight into things; shrewd.",
     "indirect_meaning": "Someone with an exceptionally sharp and accurate mind.", "very_indirect_meaning": "Detectives of literature are characterized by this."},
    {"word": "antediluvian", "meaning": "Very old-fashioned; of or belonging to a time before the flood.",
     "indirect_meaning": "Something so old it feels like it belongs to a prehistoric era.", "very_indirect_meaning": "Noah's world was literally described by this word."},
    {"word": "sycophancy", "meaning": "Excessive flattery or servile behavior toward those in power.",
     "indirect_meaning": "The behavior of someone who flatters powerful people.", "very_indirect_meaning": "Courts were filled with it; it is politics at its worst."},
    {"word": "obsequious", "meaning": "Excessively compliant or fawning.",
     "indirect_meaning": "Overly eager to please or obey someone in authority.", "very_indirect_meaning": "Shakespeare used this word for the worst kind of courtier."},
    {"word": "melancholy", "meaning": "A deep, persistent feeling of sadness without a clear cause.",
     "indirect_meaning": "A lasting sadness that seems to have no specific reason.", "very_indirect_meaning": "Keats and Chopin made it their artistic signature."},
    {"word": "equanimity", "meaning": "Mental calmness and composure, especially in difficult situations.",
     "indirect_meaning": "The ability to stay calm and balanced under pressure.", "very_indirect_meaning": "Stoic philosophers made it their highest virtue."},
    {"word": "tautology", "meaning": "Saying the same thing twice in different words; unnecessary repetition.",
     "indirect_meaning": "Repeating the same idea with different words unnecessarily.", "very_indirect_meaning": "A free gift is a classic example of it."},
    {"word": "labyrinthine", "meaning": "Resembling a labyrinth in complexity.",
     "indirect_meaning": "Extremely complex and confusing, like a maze.", "very_indirect_meaning": "Kafka built his fictional worlds from this quality."},
    {"word": "quixotic", "meaning": "Exceedingly idealistic; unrealistic and impractical.",
     "indirect_meaning": "Pursuing romantic or noble ideals that are out of touch with reality.", "very_indirect_meaning": "Named after a knight who fought windmills."},
    {"word": "serendipity", "meaning": "The occurrence of fortunate events by chance.",
     "indirect_meaning": "When something wonderful happens completely by accident.", "very_indirect_meaning": "Penicillin's discovery is history's most famous example."},
    {"word": "machiavellian", "meaning": "Cunning, scheming, and unscrupulous, especially in politics.",
     "indirect_meaning": "A political style based on deception and cunning.", "very_indirect_meaning": "A 16th century Italian wrote the handbook on it."},
    {"word": "anachronism", "meaning": "A thing belonging to a different period than the one it is placed in.",
     "indirect_meaning": "Something that is out of place because it belongs to another time.", "very_indirect_meaning": "A smartphone in a medieval painting would be one."},
    {"word": "nihilism", "meaning": "The belief that life has no meaning or purpose.",
     "indirect_meaning": "A philosophical belief that nothing in existence has real meaning.", "very_indirect_meaning": "Nietzsche spent his career wrestling with it."},
    {"word": "solipsism", "meaning": "The theory that only one's own mind is certain to exist.",
     "indirect_meaning": "The belief that nothing outside one's own mind can be proven to exist.", "very_indirect_meaning": "The ultimate form of philosophical loneliness."},
    {"word": "recalcitrant", "meaning": "Stubbornly resistant to authority or discipline.",
     "indirect_meaning": "Someone who refuses to cooperate or follow instructions.", "very_indirect_meaning": "History's great rebels were all seen as this by those in power."},
    {"word": "verisimilitude", "meaning": "The appearance of being true or real.",
     "indirect_meaning": "Something that seems so believable it feels like reality.", "very_indirect_meaning": "Great novelists pursue it obsessively."},
    {"word": "perfidious", "meaning": "Deceitful and untrustworthy; guilty of betrayal.",
     "indirect_meaning": "Someone who cannot be trusted and betrays others.", "very_indirect_meaning": "Shakespeare's villains are defined by this quality."},
    {"word": "propitious", "meaning": "Giving or indicating a good chance of success; favorable.",
     "indirect_meaning": "A favorable situation or sign that something will succeed.", "very_indirect_meaning": "Ancient Romans read bird flight to find such moments."},
    {"word": "magnanimous", "meaning": "Very generous or forgiving toward enemies or rivals.",
     "indirect_meaning": "Being generous and forgiving even toward those who wronged you.", "very_indirect_meaning": "Lincoln's Reconstruction plan was considered this."},
    {"word": "circumlocution", "meaning": "The use of many words where fewer would do; verbal evasion.",
     "indirect_meaning": "Using far too many words to say something simple.", "very_indirect_meaning": "Bureaucrats and politicians are famous practitioners."},
    {"word": "impecunious", "meaning": "Having little or no money; poor.",
     "indirect_meaning": "A formal word for someone who is very poor.", "very_indirect_meaning": "Victorian novelists frequently described artists this way."},
    {"word": "loquacious", "meaning": "Tending to talk a great deal; very chatty.",
     "indirect_meaning": "Someone who talks constantly and at great length.", "very_indirect_meaning": "Every classroom has at least one student like this."},
    {"word": "mellifluous", "meaning": "Having a smooth, rich, pleasingly sweet sound.",
     "indirect_meaning": "A sound or voice that is smooth, sweet, and musical.", "very_indirect_meaning": "Broadcasters spend careers trying to achieve it."},
    {"word": "nefarious", "meaning": "Wicked, criminal, or deeply immoral.",
     "indirect_meaning": "Describing plans or behavior that is extremely evil.", "very_indirect_meaning": "Bond villains are archetypal examples."},
    {"word": "obfuscate", "meaning": "To make something unclear or confusing deliberately.",
     "indirect_meaning": "To deliberately make something confusing or hard to understand.", "very_indirect_meaning": "Lawyers and politicians sometimes do this to hide the truth."},
    {"word": "panacea", "meaning": "A solution or remedy for all difficulties or diseases.",
     "indirect_meaning": "A supposed cure for every problem or illness.", "very_indirect_meaning": "Snake oil salesmen in the 1800s sold this concept."},
    {"word": "querulous", "meaning": "Complaining in a petulant or whining manner.",
     "indirect_meaning": "Always whining and finding fault with everything.", "very_indirect_meaning": "The character Eeyore from Winnie the Pooh is a gentle version."},
    {"word": "reticent", "meaning": "Not revealing one's thoughts or feelings readily.",
     "indirect_meaning": "A person who is quiet and reluctant to share their thoughts.", "very_indirect_meaning": "Spies and diplomats cultivate it professionally."},
    {"word": "seraphic", "meaning": "Characteristic of angels; beautifully serene.",
     "indirect_meaning": "Having an angelic, peaceful, and divine quality.", "very_indirect_meaning": "Medieval painters tried to capture it on chapel ceilings."},
    {"word": "tendentious", "meaning": "Promoting a particular cause or point of view; biased.",
     "indirect_meaning": "Media or writing that is one-sided and promotes a specific agenda.", "very_indirect_meaning": "Every piece of propaganda in history was this."},
    {"word": "ubiquitous", "meaning": "Present, appearing, or found everywhere.",
     "indirect_meaning": "Something that seems to be everywhere at the same time.", "very_indirect_meaning": "Smartphones have become this in modern society."},
    {"word": "vapid", "meaning": "Offering nothing that is stimulating or challenging; bland.",
     "indirect_meaning": "Something empty of meaning, interest, or intelligence.", "very_indirect_meaning": "Critics use it to describe entertainment without substance."},
    {"word": "wistful", "meaning": "Having a feeling of vague and regretful longing.",
     "indirect_meaning": "A gentle sadness mixed with longing for something lost.", "very_indirect_meaning": "Autumn and old photographs often inspire it."},
    {"word": "xenophile", "meaning": "A person who is attracted to foreign peoples or cultures.",
     "indirect_meaning": "Someone who loves and admires foreign cultures.", "very_indirect_meaning": "The opposite of xenophobe; travelers often become this."},
    {"word": "yore", "meaning": "Times long past; antiquity.",
     "indirect_meaning": "A poetic way of referring to the distant past.", "very_indirect_meaning": "Bards and storytellers kept its legends alive."},
    {"word": "zealotry", "meaning": "Excessive or fanatical enthusiasm for a cause.",
     "indirect_meaning": "Extreme and unreasonable dedication to a belief or cause.", "very_indirect_meaning": "Revolutions have been started and destroyed by it."},
    {"word": "abstruse", "meaning": "Difficult to understand; obscure.",
     "indirect_meaning": "Something extremely difficult to comprehend.", "very_indirect_meaning": "Advanced mathematics is often described this way by outsiders."},
    {"word": "belligerent", "meaning": "Hostile and aggressive; engaged in war.",
     "indirect_meaning": "Someone who is aggressive and eager to fight or argue.", "very_indirect_meaning": "International law has a specific definition for this status."},
    {"word": "cacophony", "meaning": "A harsh, discordant mixture of sounds.",
     "indirect_meaning": "A jarring, unpleasant mixture of loud, conflicting sounds.", "very_indirect_meaning": "Rush hour in any major city is this made audible."},
    {"word": "dichotomy", "meaning": "A division or contrast between two things that are entirely different.",
     "indirect_meaning": "A sharp division into two opposite categories.", "very_indirect_meaning": "Good vs. evil is the oldest one in storytelling."},
    {"word": "effulgent", "meaning": "Radiant; shining brilliantly.",
     "indirect_meaning": "Something that shines with a bright, glowing light.", "very_indirect_meaning": "Sunrise and full moons are described this way in poetry."},
    {"word": "fallacious", "meaning": "Based on mistaken belief; containing a logical error.",
     "indirect_meaning": "Something that seems logical but is based on false reasoning.", "very_indirect_meaning": "Aristotle catalogued dozens of these in arguments."},
    {"word": "garrulous", "meaning": "Excessively talkative, especially on trivial matters.",
     "indirect_meaning": "Someone who talks too much about unimportant things.", "very_indirect_meaning": "Different from loquacious in that the talk is particularly pointless."},
    {"word": "hegemony", "meaning": "Leadership or dominance, especially of one country over others.",
     "indirect_meaning": "The dominance of one nation or group over others.", "very_indirect_meaning": "America's post-1945 position in the world is a prime example."},
    {"word": "iconoclast", "meaning": "A person who attacks or criticizes cherished beliefs or institutions.",
     "indirect_meaning": "Someone who challenges long-held beliefs and traditions.", "very_indirect_meaning": "Every major scientific revolution was led by one."},
    {"word": "juxtapose", "meaning": "To place two things close together to create a contrasting effect.",
     "indirect_meaning": "Placing two very different things side by side for comparison.", "very_indirect_meaning": "Artists and writers use it to reveal hidden truths."},
    {"word": "kleptomania", "meaning": "A recurrent urge to steal regardless of need or profit.",
     "indirect_meaning": "An uncontrollable compulsion to steal things.", "very_indirect_meaning": "Psychologists classify it as an impulse control disorder."},
    {"word": "lethargic", "meaning": "Affected by lethargy; sluggish and apathetic.",
     "indirect_meaning": "Feeling sluggish, tired, and unable to motivate yourself.", "very_indirect_meaning": "Ancient doctors blamed it on an excess of black bile."},
    {"word": "mendacious", "meaning": "Not telling the truth; lying.",
     "indirect_meaning": "A formal word for a person who is habitually dishonest.", "very_indirect_meaning": "Historians debate whether famous leaders were this."},
    {"word": "nonchalant", "meaning": "Feeling or appearing casually calm and relaxed.",
     "indirect_meaning": "Someone who remains completely calm and unconcerned in any situation.", "very_indirect_meaning": "Cool movie characters have made this an art form."},
    {"word": "ostentatious", "meaning": "Characterized by a vulgar or pretentious display.",
     "indirect_meaning": "Showing off wealth or success in an excessive, showy way.", "very_indirect_meaning": "Baroque palaces were built to project this impression."},
    {"word": "paradigmatic", "meaning": "Serving as a typical example or pattern.",
     "indirect_meaning": "Something that serves as the perfect example of its kind.", "very_indirect_meaning": "Newton's apple is this for scientific inspiration stories."},
    {"word": "recondite", "meaning": "Not known by many people; obscure.",
     "indirect_meaning": "Knowledge that is specialized and known only by a few experts.", "very_indirect_meaning": "Ancient scholars jealously guarded such knowledge."},
    {"word": "supercilious", "meaning": "Behaving as though one is superior to others.",
     "indirect_meaning": "A person who acts as though everyone else is beneath them.", "very_indirect_meaning": "Aristocrats of the 19th century were trained to be this."},
    {"word": "truculent", "meaning": "Eager or quick to argue or fight; aggressively defiant.",
     "indirect_meaning": "Someone who is always ready for an argument or confrontation.", "very_indirect_meaning": "Certain historical generals were admired and feared for it."},
    {"word": "umbrage", "meaning": "Offense or annoyance.",
     "indirect_meaning": "The feeling of being offended or annoyed by someone.", "very_indirect_meaning": "Victorian diplomats took it over the slightest perceived slight."},
    {"word": "voluminous", "meaning": "Occupying or containing a large volume; very large.",
     "indirect_meaning": "Something extremely large in size, quantity, or extent.", "very_indirect_meaning": "Tolstoy's novels are the literary benchmark for this quality."},
    {"word": "whimsical", "meaning": "Playfully quaint or fanciful; not serious.",
     "indirect_meaning": "Something that is charmingly playful and imaginative.", "very_indirect_meaning": "Lewis Carroll built an entire world from this quality."},
    {"word": "inexorable", "meaning": "Impossible to stop or prevent.",
     "indirect_meaning": "A force or process that cannot be slowed or stopped.", "very_indirect_meaning": "Time is the most familiar example humans encounter."},
    {"word": "proclivity", "meaning": "A tendency to choose or do something regularly.",
     "indirect_meaning": "A natural inclination or tendency toward a behavior.", "very_indirect_meaning": "Criminal psychologists study these in offender profiling."},
    {"word": "sophistry", "meaning": "The use of clever but false arguments.",
     "indirect_meaning": "Arguing using logic that sounds good but is actually flawed.", "very_indirect_meaning": "Ancient Greek philosophers invented and denounced it."},
    {"word": "tumultuous", "meaning": "Making a loud, confused noise; in a state of confusion.",
     "indirect_meaning": "Describing a chaotic, noisy, and disorderly situation.", "very_indirect_meaning": "Revolutionary France was the definition of this period."},
    {"word": "unequivocal", "meaning": "Leaving no doubt; unambiguous.",
     "indirect_meaning": "Completely clear and certain, with no room for doubt.", "very_indirect_meaning": "Great leaders are known for speaking in this manner."},
    {"word": "vituperative", "meaning": "Bitter and abusive in language.",
     "indirect_meaning": "Language that is harshly critical and insulting.", "very_indirect_meaning": "Political debates have often descended into this."},
    {"word": "winsome", "meaning": "Attractive or appealing in a fresh, innocent way.",
     "indirect_meaning": "Charmingly attractive and likable in a gentle, innocent way.", "very_indirect_meaning": "Disney animated characters are designed to be this."},
    {"word": "xenolith", "meaning": "A fragment of rock embedded within an igneous rock.",
     "indirect_meaning": "A piece of foreign rock trapped inside another type of rock.", "very_indirect_meaning": "Geologists use them to study the Earth's deep crust."},
    {"word": "yen", "meaning": "A longing or yearning; also the Japanese currency.",
     "indirect_meaning": "A deep, persistent desire for something.", "very_indirect_meaning": "Both a craving and the currency of the world's third-largest economy."},
    {"word": "zymology", "meaning": "The study of fermentation.",
     "indirect_meaning": "The scientific study of how fermentation works.", "very_indirect_meaning": "Every brewer and winemaker applies its principles."},
    {"word": "apostrophe", "meaning": "A punctuation mark used to show possession or omission.",
     "indirect_meaning": "A grammar mark that shows ownership or missing letters.", "very_indirect_meaning": "Its misuse starts culture wars on the internet."},
    {"word": "burgeoning", "meaning": "Growing or developing rapidly.",
     "indirect_meaning": "Something expanding or growing very quickly.", "very_indirect_meaning": "Silicon Valley in the 1990s was the definition of this."},
    {"word": "catharsis", "meaning": "The release of emotional tension through art or experience.",
     "indirect_meaning": "An emotional release and relief through a powerful experience.", "very_indirect_meaning": "Aristotle said tragedy provides it to the audience."},
    {"word": "draconian", "meaning": "Excessively harsh or severe.",
     "indirect_meaning": "Describing rules or punishments that are extremely strict.", "very_indirect_meaning": "Named after an Athenian lawmaker who prescribed death for minor crimes."},
    {"word": "epistemic", "meaning": "Relating to knowledge or the conditions for acquiring it.",
     "indirect_meaning": "Describing something related to the nature of knowledge.", "very_indirect_meaning": "Philosophers study these questions when asking 'what can we know?'"},
    {"word": "filibuster", "meaning": "A prolonged speech to delay legislation.",
     "indirect_meaning": "Talking for so long that no vote can be taken.", "very_indirect_meaning": "American senators have read phone books to use this tactic."},
    {"word": "grandiloquent", "meaning": "Using unnecessarily long and showy words.",
     "indirect_meaning": "Speaking or writing in a pompous and overly elaborate way.", "very_indirect_meaning": "Victorian politicians were notorious practitioners of this style."},
    {"word": "hubris", "meaning": "Excessive pride or self-confidence, leading to downfall.",
     "indirect_meaning": "Dangerous overconfidence that leads to catastrophic failure.", "very_indirect_meaning": "Every Greek tragedy is built on a character possessing this."},
    {"word": "imbroglio", "meaning": "An extremely confused, complicated, or embarrassing situation.",
     "indirect_meaning": "A complicated and confusing situation that is hard to escape.", "very_indirect_meaning": "Political scandals in Italian history were often described this way."},
    {"word": "jejune", "meaning": "Naive, simple, and superficial; lacking in interest or significance.",
     "indirect_meaning": "Something that is overly simplistic, boring, or lacking depth.", "very_indirect_meaning": "Critics use it to dismiss unsophisticated arguments."},
    {"word": "kafkaesque", "meaning": "Having a nightmarishly complex, bizarre, or illogical quality.",
     "indirect_meaning": "A situation that is absurdly complicated and bureaucratic.", "very_indirect_meaning": "Named after the writer who turned bureaucracy into horror fiction."},
    {"word": "lachrymose", "meaning": "Tearful or given to weeping.",
     "indirect_meaning": "Someone who cries easily or frequently.", "very_indirect_meaning": "Dickens wrote characters that made audiences openly weep."},
    {"word": "malapropism", "meaning": "The mistaken use of a word in place of a similar-sounding one.",
     "indirect_meaning": "When someone confuses a word with a similar-sounding incorrect one.", "very_indirect_meaning": "Named after a character in an 18th century play who constantly did it."},
    {"word": "nebulous", "meaning": "In the form of a cloud; vague and unclear.",
     "indirect_meaning": "Something vague, unclear, or without definite form.", "very_indirect_meaning": "Early universe matter was literally and figuratively this."},
    {"word": "onomatopoeia", "meaning": "Words that imitate the sounds they describe.",
     "indirect_meaning": "A word that sounds like what it describes, like 'buzz' or 'crash.'", "very_indirect_meaning": "Poets use it to make language feel alive."},
    {"word": "palimpsest", "meaning": "A manuscript where original writing is erased for reuse.",
     "indirect_meaning": "A surface where layers of past writing or history are hidden beneath.", "very_indirect_meaning": "Cities are architectural versions of it — built on top of themselves."},
    {"word": "quagmire", "meaning": "A soft boggy area of land; a difficult or precarious situation.",
     "indirect_meaning": "A situation that is difficult to escape from, like quicksand.", "very_indirect_meaning": "Vietnam and Afghanistan both became this metaphor for superpowers."},
    {"word": "ratiocination", "meaning": "The process of logical and careful reasoning.",
     "indirect_meaning": "The act of thinking through something carefully and logically.", "very_indirect_meaning": "Sherlock Holmes is its fictional personification."},
    {"word": "sanguine", "meaning": "Optimistic, especially in difficult situations.",
     "indirect_meaning": "Someone who remains hopeful and positive even in bad times.", "very_indirect_meaning": "Medieval medicine blamed temperament on blood, making this its mood."},
    {"word": "transmogrify", "meaning": "To transform in a surprising or magical manner.",
     "indirect_meaning": "To change something into a completely different form.", "very_indirect_meaning": "Calvin and Hobbes had a cardboard box that did exactly this."},
    {"word": "unctuous", "meaning": "Excessively flattering in an insincere way.",
     "indirect_meaning": "Someone who acts overly nice in a way that feels fake and calculated.", "very_indirect_meaning": "Uriah Heep in Dickens is the literary prototype."},
    {"word": "vicarious", "meaning": "Experienced through another person rather than oneself.",
     "indirect_meaning": "Experiencing something through someone else's actions or feelings.", "very_indirect_meaning": "Every reader of fiction lives vicariously through its characters."},
    {"word": "weltanschauung", "meaning": "A comprehensive worldview or philosophy of life.",
     "indirect_meaning": "A person's or culture's complete view of the world and existence.", "very_indirect_meaning": "German idealism produced some of history's most elaborate ones."},
]


def get_words_by_difficulty(difficulty: str) -> list:
    """Return the word list corresponding to the given difficulty string."""
    mapping = {
        "easy": EASY_WORDS,
        "medium": MEDIUM_WORDS,
        "hard": HARD_WORDS,
    }
    return mapping.get(difficulty.lower(), EASY_WORDS)

# ── top-up entries to hit the 100-per-difficulty requirement ──────────────────

EASY_WORDS += [
    {"word": "signal", "meaning": "A sign or indication used to convey information.",
     "indirect_meaning": "What traffic lights and phones both send.", "very_indirect_meaning": "Without it, communication collapses."},
    {"word": "ticket", "meaning": "A piece of paper giving the holder the right to enter or travel.",
     "indirect_meaning": "You need one to board a train or see a movie.", "very_indirect_meaning": "The gatekeeper to events, journeys, and concerts."},
]

MEDIUM_WORDS += [
    {"word": "abstract", "meaning": "Existing in thought or as an idea without physical form.",
     "indirect_meaning": "An idea that cannot be touched or seen directly.", "very_indirect_meaning": "Justice and love are perfect examples."},
    {"word": "analogy", "meaning": "A comparison between two things to explain or clarify.",
     "indirect_meaning": "Explaining something unfamiliar by likening it to something familiar.", "very_indirect_meaning": "Socrates used them constantly to trap his opponents."},
    {"word": "momentum", "meaning": "The force or speed of movement; impetus.",
     "indirect_meaning": "The unstoppable feeling a team gets when things go well.", "very_indirect_meaning": "Physics says it equals mass times velocity."},
    {"word": "narrative", "meaning": "A spoken or written account of connected events.",
     "indirect_meaning": "The story or account given to explain a series of events.", "very_indirect_meaning": "Historians and politicians both fight to control it."},
    {"word": "obscure", "meaning": "Not discovered or known about; hard to find.",
     "indirect_meaning": "Something known by very few people.", "very_indirect_meaning": "Great art often starts its life this way."},
    {"word": "premise", "meaning": "A statement or idea that forms the basis of an argument.",
     "indirect_meaning": "The foundational idea that an argument is built upon.", "very_indirect_meaning": "Every logical proof begins with one."},
]

HARD_WORDS += [
    {"word": "apocryphal", "meaning": "Of doubtful authenticity; widely circulated but probably not true.",
     "indirect_meaning": "A story that everyone repeats but that is probably invented.", "very_indirect_meaning": "Newton's apple is considered this by many historians."},
    {"word": "chicanery", "meaning": "The use of trickery to achieve goals.",
     "indirect_meaning": "Clever deception used to get what you want.", "very_indirect_meaning": "Con artists and courtroom lawyers are accused of it."},
    {"word": "corpulent", "meaning": "Having a large, heavy body; obese.",
     "indirect_meaning": "A formal or literary word for someone who is overweight.", "very_indirect_meaning": "Henry VIII is history's most famous example in portraiture."},
    {"word": "dilettante", "meaning": "A person who cultivates an interest in a subject superficially.",
     "indirect_meaning": "Someone who dabbles in many things without mastering any.", "very_indirect_meaning": "The Renaissance ideal was the opposite — the true polymath."},
    {"word": "enervate", "meaning": "To weaken someone physically or mentally.",
     "indirect_meaning": "To drain all energy and motivation from someone.", "very_indirect_meaning": "Tropical heat was said to do this to colonists."},
    {"word": "fastidious", "meaning": "Very attentive to accuracy and detail; hard to please.",
     "indirect_meaning": "Someone who demands perfection and notices every flaw.", "very_indirect_meaning": "Surgeons and Swiss watchmakers are professionally this."},
    {"word": "gainsay", "meaning": "To deny or contradict.",
     "indirect_meaning": "To speak against or dispute what someone has said.", "very_indirect_meaning": "Few could this a philosopher in full argument."},
    {"word": "hapless", "meaning": "Unfortunate; having bad luck.",
     "indirect_meaning": "Someone who is perpetually unlucky through no fault of their own.", "very_indirect_meaning": "Dickens populated his novels with them."},
    {"word": "intransigent", "meaning": "Refusing to change one's views or to agree.",
     "indirect_meaning": "Completely unwilling to compromise or negotiate.", "very_indirect_meaning": "Peace talks often fail because one side is this."},
]
